const rawInput=document.querySelector('#rawInput'),decodeBtn=document.querySelector('#decodeBtn'),resultContent=document.querySelector('#resultContent'),emptyState=document.querySelector('#emptyState'),resultTitle=document.querySelector('#resultTitle'),copyBtn=document.querySelector('#copyBtn'),camera=document.querySelector('#camera'),videoWrap=document.querySelector('#videoWrap'),cameraHint=document.querySelector('#cameraHint'),cameraState=document.querySelector('#cameraState');let stream,scanTimer,lastResult='';
const airlineNames={'125':'British Airways','180':'Korean Air','235':'Turkish Airlines','297':'China Airlines','695':'EVA Air','781':'China Eastern Airlines','112':'China Cargo Airlines'};
function dayOfYearToDate(day){if(!day||day==='000')return '未提供';const y=new Date().getFullYear();const d=new Date(y,0);d.setDate(+day);return new Intl.DateTimeFormat('zh-TW',{month:'short',day:'numeric'}).format(d)}
function field(label,value,full=false){return `<div class="data-item ${full?'full':''}"><div class="data-label">${label}</div><div class="data-value">${value||'—'}</div></div>`}
function clean(v){return (v||'').trim().replace(/\s+/g,' ')}
function parseBcbp(raw){const s=raw.replace(/[\r\n]/g,'');if(!/^M\d/.test(s)||s.length<60)return null;const legs=+s[1]||1,passenger=clean(s.slice(2,22)).replace('/', ' / '),pnr=clean(s.slice(23,30)),from=clean(s.slice(30,33)),to=clean(s.slice(33,36)),carrier=clean(s.slice(36,39)),flight=clean(s.slice(39,44)),julian=clean(s.slice(44,47)),compartment=clean(s.slice(47,48)),seat=clean(s.slice(48,52)),sequence=clean(s.slice(52,57)),status=clean(s.slice(57,58));return{type:'登機證（IATA BCBP）',passenger,pnr,from,to,carrier,flight,date:dayOfYearToDate(julian),seat,compartment,sequence,status,legs,raw:s}}
function parseBag(raw){const found=raw.replace(/[^0-9]/g,'').match(/\d{10}/);if(!found)return null;const tag=found[0],airline=tag.slice(0,3);return{type:'行李牌',tag,airline,airlineName:airlineNames[airline]||'航空公司代碼 '+airline,serial:tag.slice(3),raw}}
function show(data){emptyState.hidden=true;resultContent.hidden=false;resultTitle.textContent=data.type;let html='';if(data.passenger){html+=`<div class="result-type">已辨識 <span class="pill">${data.legs} 航段</span></div><div class="route">${data.from} <span aria-hidden="true">→</span> ${data.to}</div><div class="data-grid">${field('旅客姓名',data.passenger,true)}${field('航班',`${data.carrier} ${data.flight}`)}${field('出發日期',data.date)}${field('座位',data.seat)}${field('艙等代碼',data.compartment)}${field('訂位代號',data.pnr)}${field('登機序號',data.sequence)}${field('狀態代碼',data.status)}</div>`}else if(data.tag){html+=`<div class="result-type">已辨識 <span class="pill">10 位數標籤</span></div><div class="data-grid">${field('行李牌號碼',data.tag,true)}${field('航空公司前三碼',data.airline)}${field('可能的航空公司',data.airlineName)}${field('行李流水號',data.serial,true)}</div><p class="warning">行李牌條碼通常不含航點與航班；此處僅解讀可由 10 位數標籤可靠取得的資訊。</p>`}else{html=`<p class="warning">此內容看起來不是可辨識的 IATA BCBP 登機證或 10 位數行李牌。請確認掃描是否完整，或改貼上原始條碼字串。</p>`}html+=`<div class="data-label" style="margin-top:16px">原始內容</div><div class="raw-box">${data.raw.replace(/</g,'&lt;')}</div>`;resultContent.innerHTML=html;lastResult=resultContent.innerText;copyBtn.disabled=false}
function decode(){const raw=rawInput.value.trim();if(!raw)return;show(parseBcbp(raw)||parseBag(raw)||{raw,type:'無法自動分類'})}
decodeBtn.onclick=decode;rawInput.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')decode()});copyBtn.onclick=async()=>{await navigator.clipboard.writeText(lastResult);copyBtn.textContent='已複製';setTimeout(()=>copyBtn.textContent='複製',1400)};
async function scanImage(source){if(!('BarcodeDetector'in window)){cameraState.textContent='此瀏覽器不支援自動掃描';return}try{const detector=new BarcodeDetector({formats:['pdf417','aztec','qr_code','code_128','data_matrix']});const codes=await detector.detect(source);if(codes[0]){rawInput.value=codes[0].rawValue;decode();stopCamera()}}catch(e){cameraState.textContent='未能辨識條碼，請再試一次'}}
document.querySelector('#imageInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;const img=new Image();img.onload=()=>{scanImage(img);URL.revokeObjectURL(img.src)};img.src=URL.createObjectURL(file)};
function stopCamera(){if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;clearInterval(scanTimer);videoWrap.classList.remove('active');cameraHint.hidden=false;cameraState.textContent='相機待命';document.querySelector('#startCamera').textContent='開啟相機'}
document.querySelector('#startCamera').onclick=async()=>{if(stream)return stopCamera();try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});camera.srcObject=stream;await camera.play();videoWrap.classList.add('active');cameraHint.hidden=true;cameraState.textContent='正在掃描';document.querySelector('#startCamera').textContent='關閉相機';scanTimer=setInterval(()=>scanImage(camera),900)}catch(e){cameraState.textContent='無法使用相機'}};
